language: java

sudo: false

notifications:
  email:
    recipients:
      - ismaelhommani@gmail.com
    on_success: change
    on_failure: always

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - python2.7

env:
  matrix:
    - CUSTOM_JDK="default"
    - CUSTOM_JDK="oraclejdk8"
    - CUSTOM_JDK="oraclejdk7"
    - CUSTOM_JDK="openjdk7"

matrix:
  exclude:
     # On OSX, run with default JDK only.
     - os: osx
       env: CUSTOM_JDK="oraclejdk8"
     - os: osx
       env: CUSTOM_JDK="oraclejdk7"
     - os: osx
       env: CUSTOM_JDK="openjdk7"
     # On Linux, run with specific JDKs only.
     - os: linux
       env: CUSTOM_JDK="default"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use "$CUSTOM_JDK"; fi
  - export TOX_ENV=py27
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export TOX_HOME=$HOME/Library/Python/2.7/bin; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export TOX_HOME=$HOME/.local/bin; fi

install:
  - travis_retry mvn install clean -U -DskipTests=true -f java/starter/pom.xml
  - travis_retry mvn install clean -U -DskipTests=true -f java/examples/pom.xml
  - if [[ "$CUSTOM_JDK" == "oraclejdk8" || "$CUSTOM_JDK" == "default" ]]; then travis_retry mvn install clean -U -DskipTests=true -f java/examples-java8/pom.xml; fi
  - if pip list | grep tox; then TOX_FILE=`which tox` ; export TOX_HOME=`dirname $TOX_FILE`; fi
  - if ! pip list | grep tox; then travis_retry pip install tox --user; fi

script:
  - travis_retry mvn install -U -f java/starter/pom.xml
  - travis_retry mvn install -U -f java/examples/pom.xml
  - if [[ "$CUSTOM_JDK" == "oraclejdk8" || "$CUSTOM_JDK" == "default" ]]; then travis_retry mvn install -U -f java/examples-java8/pom.xml; fi
  - travis_retry $TOX_HOME/tox -e $TOX_ENV -c python/tox.ini
